### ISSUE TITLE
bildschirrmschoner

### ISSUE THREAD

**Issue by norbertB188** [xXBJXx/ioBroker.fully-tablet-control#120]
2021-01-14 17:44:49.642  - [31merror[39m: fully-tablet-control.0 (18683) fire send status for ScreensaverOn could not be sent => The "url" argument must be of type string. Received undefined, stack: TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Url.parse (url.js:159:3)
    at Object.urlParse [as parse] (url.js:154:13)
    at dispatchHttpRequest (/opt/iobroker/node_modules/axios/lib/adapters/http.js:91:22)
    at new Promise (<anonymous>)
    at httpAdapter (/opt/iobroker/node_modules/axios/lib/adapters/http.js:46:10)
    at dispatchRequest (/opt/iobroker/node_modules/axios/lib/core/dispatchRequest.js:52:10)
    at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.fully-tablet-control/main.js:2835:21)

**Comment by xXBJXx** [comment]
fixed in v0.3.2-beta.0
